server:
  port: 2333
  address: 0.0.0.0

plugins:
    dir: ./plugins

lavalink:
  server:
    password: "A6xHk705Ssa19732819"
    sources:
      youtube: false
      soundcloud: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true
    trackStuckThresholdMs: 30000

youtube:
  enabled: true
  search: true
  clients:
    - ANDROID_TESTSUITE
    - MUSIC
    - WEB
    - WEBEMBEDDED
    - TVHTML5EMBEDDED
    - IOS

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG